#!/bin/bash

prnt_acpi ()
{
    bttry=$(acpi -b)
    adptr=$(acpi -a)
    thrml=$(acpi -tf)
    bttry="${bttry#*, }"
    bttry="${bttry%%%*}"
    bttry=$(printf "%03d" ${bttry})

    if [[ "$adptr" == *on-line* ]]; then
        echo -ne "\x05Pwr \x07${bttry}"
    else
        echo -ne "\x05Pwr \x0b${bttry}"
    fi
}

prnt_amxr ()
{
    mastr=$(amixer get Master)

    if [[ "$mastr" == *off* ]]; then
        echo -ne "Vol \x0bmut"
    else
        mastr="${mastr#*[}"
        l="%*"
        mastr="${mastr%$l}"
        mastr=$(printf "%03d" ${mastr})
        echo -ne "Vol \x08${mastr}"
    fi
}

prnt_date ()
{
    echo -ne "$(date "+%a %m.%d %H:%M\x0e:%S\x0d")"
}

prnt_ncfg ()
{
    crrnt="$(netcfg current)"
    crrnt="${crrnt#*-}"
    if [[ "$crrnt" == "" ]]; then
        if [[ "$(ifconfig eth0)" == *RUNNING* ]]; then
            echo -ne "[\x06eth0\x05]"
        else
            echo -ne "[\x0boff\x05]"
        fi
    else
        echo -ne "[\x06${crrnt}\x05]"
    fi
}

prnt_ncmp ()
{
    music="$(ncmpcpp --now-playing)"
    music="${music#* }"
    music="${music/ - / \x03>\x01 }"
    if [[ ! "$music" == "" ]]; then
        echo -ne "${music}"
    fi
}

prnt_case ()
{
    strng="$(prnt_ncmp) \x04¦\x05 $(prnt_ncfg) $(prnt_amxr) $(prnt_acpi) \x0c¦\x0d $(prnt_date) \x0c¨\x05§"
    strng="${strng/$/}"
    case $1 in
    lower)
        echo -ne ${strng} | tr '[A-Z]' '[a-z]'
        ;;
    upper)
        echo -ne ${strng} | tr '[a-z]' '[A-Z]'
        ;;
    *)
        echo -ne ${strng}
        ;;
    esac
}

while true; do
    xsetroot -name "$(prnt_case)"
    sleep .01
done
