#!/bin/bash

prnt_acpi ()
{
    bttry=$(acpi -b)
    adptr=$(acpi -a)
    thrml=$(acpi -tf)
    bttry="${bttry#*, }"
    bttry="${bttry%%%*}"
    bttry=$(printf "%03d" ${bttry})

    if [[ "$adptr" == *on-line* ]]; then
        echo -ne "Pwr ${bttry}"
    else
        echo -ne "Pwr ${bttry}"
    fi
}

prnt_amxr ()
{
    mastr=$(amixer get Master)

    if [[ "$mastr" == *off* ]]; then
        echo -ne "Vol mut"
    else
        mastr="${mastr#*[}"
        l="%*"
        mastr="${mastr%$l}"
        mastr=$(printf "%03d" ${mastr})
        echo -ne "Vol ${mastr}"
    fi
}

prnt_date ()
{
    echo -ne "$(date "+%a %m.%d | %H:%M")"
}

prnt_ncfg ()
{
    crrnt="$(netcfg current)"
    crrnt="${crrnt#*-}"
    if [[ "$crrnt" == "" ]]
    then
        crrnt="off"
    fi
    echo -ne ${crrnt}
}

prnt_ncmp ()
{
    music="$(ncmpcpp --now-playing)"
    music="${music#* }"
    echo -ne ${music}
}

prnt_case ()
{
    strng="$(prnt_ncmp) | $(prnt_ncfg) | $(prnt_amxr) | $(prnt_acpi) | $(prnt_date)"
    case $1 in
    lower)
        echo -ne ${strng} | tr '[A-Z]' '[a-z]'
        ;;
    upper)
        echo -ne ${strng} | tr '[a-z]' '[A-Z]'
        ;;
    *)
        echo -ne ${strng}
        ;;
    esac
}

while true
do
    xsetroot -name "$(prnt_case)"
    sleep .01
done
