#!/bin/bash

cp -a ~/{dwm,scripts,.gtkrc-2.0,.bash_profile,.bashrc,.emacs,.hgrc,.ncmpcpp,.rtorrent.rc,colors.txt,.vimrc,.xbindkeysrc,.xinitrc,.Xresources} ~/hz
cd ~/hz
git add . -A
git commit -m 'auto update'
git push -u origin master
