#!/bin/bash

print_pwr() {
    battery="$(acpi -b)"
    battery="${battery#*, }"
    battery="${battery%%%*}"
    battery="$(printf "%03d" ${battery})"
    if [[ "$(acpi -a)" == *on-line* ]]; then
        battery="Pwr \x07${battery}"
    else
        battery="Pwr \x0b${battery}"
    fi
    echo -ne ${battery}
}

print_vol() {
    master=$(amixer get Master)
    if [[ "$master" == *off* ]]; then
        master="Vol \x0bmut"
    else
        master="${master#*[}"
        s="%*"
        master="${master%$s}"
        master="$(printf "%03d" ${master})"
        master="Vol \x08${master}"
    fi
    echo -ne ${master}
}

print_date() {
    echo -ne "$(date "+%a %m.%d %H:%M\x0e:%S\x0d")"
}

print_netcfg() {
    current="$(netcfg current)"
    current="${current#*-}"
    if [[ "$current" == "" ]]; then
        if [[ "$(ifconfig eth0)" == *RUNNING* ]]; then
            current="Net \x06eth0"
        else
            current="Net \x0boff"
        fi
    else
        current="Net \x06${current}"
    fi
    echo -ne ${current}
}

print_music() {
    music="$(ncmpcpp --now-playing)"
    music="${music#* }"
    music="${music/ - / \x03-\x01 }"
    if [[ ! "$music" == "" ]]; then
        echo -ne ${music}
    fi
}

print_status() {
    status="$(print_music) \x04¦\x05 $(print_netcfg) \x05$(print_vol) \x05$(print_pwr) \x0c¦\x0d $(print_date) \x0c¨\x05©"
    status="${status/$/}"
    case $1 in
    lower)
        echo -ne ${status} | tr '[A-Z]' '[a-z]'
        ;;
    upper)
        echo -ne ${status} | tr '[a-z]' '[A-Z]'
        ;;
    *)
        echo -ne ${status}
        ;;
    esac
}

while true; do
    xsetroot -name "$(print_status)"
    sleep .1s
done
